INSERT INTO pokemon (id, url, name, damage, health) VALUES
(1L, '/assets/pokemons/Bulbasaur.png','Bulbasaur', 65, 45),
(2L, '/assets/pokemons/Ivysaur.png', 'Ivysaur', 80, 60),
(3L, '/assets/pokemons/Venusaur.png', 'Venusaur', 100, 80),
(4L, '/assets/pokemons/Charmander.png', 'Charmander', 60, 39),
(5L, '/assets/pokemons/Charmeleon.png', 'Charmeleon', 80, 58),
(6L, '/assets/pokemons/Charizard.png', 'Charizard', 109, 78),
(7L, '/assets/pokemons/Squirtle.png', 'Squirtle', 50, 44),
(8L, '/assets/pokemons/Wartortle.png', 'Watortle', 65, 59),
(9L, '/assets/pokemons/Blastoise.png', 'Blastoise', 85, 79),
(10L, '/assets/pokemons/Caterpie.png', 'Caterpie', 30, 45),
(11L, '/assets/pokemons/Metapod.png', 'Metapod', 50, 25),
(12L, '/assets/pokemons/Butterfree.webp', 'Butterfree', 80, 60),
(13L, '/assets/pokemons/Weedle.png', 'Weedle', 35, 40),
(14L, '/assets/pokemons/Kakuna.png', 'Kakuna', 25, 40),
(15L, '/assets/pokemons/Beedrill.png', 'Beedrill', 80, 65),
(16L, '/assets/pokemons/Pidgey.png', 'Pidgey', 45, 40),
(17L, '/assets/pokemons/Pidgeotto.png', 'Pidgeotto', 60, 63),
(18L, '/assets/pokemons/Pidgeot.png', 'Pidgeot', 80, 83),
(19L, '/assets/pokemons/Rattata.png', 'Rattata', 56, 30),
(20L, '/assets/pokemons/Raticate.png', 'Raticate', 81, 55),
(21L, '/assets/pokemons/Spearow.png', 'Spearow', 60, 40),
(22L, '/assets/pokemons/Fearow.png', 'Fearow', 90, 65),
(23L, '/assets/pokemons/Ekans.png', 'Ekans', 60, 35),
(24L, '/assets/pokemons/Arbok.png', 'Arbok', 85, 60),
(25L, '/assets/pokemons/Pikachu.png', 'Pikachu', 55, 35),
(26L, '/assets/pokemons/Raichu.webp', 'Raichu', 90, 60),
(27L, '/assets/pokemons/Sandshrew.png', 'Sandshrew', 75, 50),
(28L, '/assets/pokemons/Sandslash.png', 'Sandslash', 100, 75),
(29L, '/assets/pokemons/Nidoran.png', 'Nidoran♀', 47, 55),
(30L, '/assets/pokemons/Nidorina.png', 'Nidorina', 62, 70),
(31L, '/assets/pokemons/Nidoqueen.png', 'Nidoqueen', 82, 90),
(32L, '/assets/pokemons/NidoranM.png', 'Nidoran♂', 57, 46),
(33L, '/assets/pokemons/Nidorino.png', 'Nidorino', 72, 61),
(34L, '/assets/pokemons/Nidoking.png', 'Nidoking', 92, 81),
(35L, '/assets/pokemons/Clefairy.png', 'Clefairy', 60, 70),
(36L, '/assets/pokemons/Clefable.png', 'Clefable', 85, 95),
(37L, '/assets/pokemons/Vulpix.png', 'Vulpix', 50, 38),
(38L, '/assets/pokemons/Ninetales.png', 'Ninetales', 81, 73),
(39L, '/assets/pokemons/Jigglypuff.png', 'Jigglypuff', 45, 115),
(40L, '/assets/pokemons/Wigglytuff.png', 'Wigglytuff', 75, 140),
(41L, '/assets/pokemons/Zubat.png', 'Zubat', 45, 40),
(42L, '/assets/pokemons/Golbat.png', 'Golbat', 80, 75),
(43L, '/assets/pokemons/Oddish.png', 'Oddish', 75, 45),
(44L, '/assets/pokemons/Gloom.png', 'Gloom', 85, 60),
(45L, '/assets/pokemons/Vileplume.png', 'Vileplume', 100, 75),
(46L, '/assets/pokemons/Paras.png', 'Paras', 70, 35),
(47L, '/assets/pokemons/Parasect.png', 'Parasect', 95, 60),
(48L, '/assets/pokemons/Venonat.png', 'Venonat', 55, 60),
(49L, '/assets/pokemons/Venomoth.png', 'Venomoth', 90, 70),
(50L, '/assets/pokemons/Diglett.png', 'Diglett', 55, 10),
(51L, '/assets/pokemons/Dugtrio.png', 'Dugtrio', 80, 35),
(52L, '/assets/pokemons/Meowth.png', 'Meowth', 45, 40),
(53L, '/assets/pokemons/Persian.png', 'Persian', 70, 65),
(54L, '/assets/pokemons/Psyduck.png', 'Psyduck', 65, 50),
(55L, '/assets/pokemons/Golduck.png', 'Golduck', 95, 80),
(56L, '/assets/pokemons/Mankey.png', 'Mankey', 80, 40),
(57L, '/assets/pokemons/Primeape.png', 'Primeape', 105 ,65),
(58L, '/assets/pokemons/Growlithe.png', 'Growlithe', 70, 55),
(59L, '/assets/pokemons/Arcanine.png', 'Arcanine', 110, 90),
(60L, '/assets/pokemons/Poliwag.png', 'Poliwag', 50, 40),
(61L, '/assets/pokemons/Poliwhirl.png', 'Poliwhirl', 65, 65),
(62L, '/assets/pokemons/Poliwrath.png', 'Poliwrath', 85, 90),
(63L, '/assets/pokemons/Abra.png', 'Abra', 105 ,25),
(64L, '/assets/pokemons/Kadabra.png', 'Kadabra', 120, 40),
(65L, '/assets/pokemons/Alakazam.png', 'Alakazam', 135, 55),
(66L, '/assets/pokemons/Machop.png', 'Machop', 80, 70),
(67L, '/assets/pokemons/Machoke.png', 'Machoke', 100, 80),
(68L, '/assets/pokemons/Machamp.png', 'Machamp', 130, 90),
(69L, '/assets/pokemons/Bellsprout.png', 'Bellsprout', 75, 50),
(70L, '/assets/pokemons/Weepinbell.png', 'Weepinbell', 90, 65),
(71L, '/assets/pokemons/Victreebel.png', 'Victreebell', 105, 80),
(72L, '/assets/pokemons/Tentacool.png', 'Tentacool', 50, 40),
(73L, '/assets/pokemons/Tentacruel.png', 'Tentacruel', 80, 80),
(74L, '/assets/pokemons/Geodude.png', 'Geodude', 80, 40),
(75L, '/assets/pokemons/Graveler.png', 'Graveler', 95, 55),
(76L, '/assets/pokemons/Golem.png', 'Golem', 110, 80),
(77L, '/assets/pokemons/Ponyta.png', 'Ponyta', 85, 50),
(78L, '/assets/pokemons/Rapidash.png', 'Rapidash', 100, 65),
(79L, '/assets/pokemons/Slowpoke.png', 'Slowpoke', 65, 90),
(80L, '/assets/pokemons/Slowbro.png', 'Slowbro', 100, 95),
(81L, '/assets/pokemons/Magnemite.png', 'Magnemite', 95, 25),
(82L, '/assets/pokemons/Magneton.png', 'Magnetom', 120, 50),
(83L, '/assets/pokemons/Farfetch%27d.png', 'Farfetch''d', 65, 52),
(84L, '/assets/pokemons/Doduo.png', 'Doduo', 85, 35),
(85L, '/assets/pokemons/Dodrio.png', 'Dodrio', 110, 60),
(86L, '/assets/pokemons/Seel.png', 'Seel', 55, 65),
(87L, '/assets/pokemons/Dewgong.png', 'Dewgong', 70, 90),
(88L, '/assets/pokemons/Grimer.png', 'Grimer', 80, 80),
(89L, '/assets/pokemons/Muk.png', 'Muk', 105, 105),
(90L, '/assets/pokemons/Shellder.png', 'Shellder', 65, 30),
(91L, '/assets/pokemons/Cloyster.png', 'Cloyster', 95, 50),
(92L, '/assets/pokemons/Gastly.png', 'Gastly', 100, 30),
(93L, '/assets/pokemons/Haunter.png', 'Haunter', 115, 45),
(94L, '/assets/pokemons/Gengar.png', 'Gengar', 130, 60),
(95L, '/assets/pokemons/Onix.png', 'Onix', 45, 35),
(96L, '/assets/pokemons/Drowzee.png', 'Drowzee', 48, 60),
(97L, '/assets/pokemons/Hypno.png', 'Hypno', 73, 85),
(98L, '/assets/pokemons/Krabby.png', 'Krabby', 105, 30),
(99L, '/assets/pokemons/Kingler.png', 'Kingler', 130, 55),
(100L, '/assets/pokemons/Voltorb.png', 'Voltorb', 55, 40),
(101L, '/assets/pokemons/Electrode.png', 'Electrode', 80, 50),
(102L, '/assets/pokemons/Exeggcute.png', 'Exeggcute', 60, 60),
(103L, '/assets/pokemons/Exeggutor.png', 'Exeggutor', 125, 95),
(104L, '/assets/pokemons/Cubone.png', 'Cubone', 50, 50),
(105L, '/assets/pokemons/Marowak.png', 'Marowak', 80, 60),
(106L, '/assets/pokemons/Hitmonlee.png', 'Hitmonlee', 120, 50),
(107L, '/assets/pokemons/Hitmonchan.png', 'Hitmonchan', 105, 50),
(108L, '/assets/pokemons/Lickitung.png', 'Lickitung', 55 ,90 ),
(109L, '/assets/pokemons/Koffing.png', 'Koffing', 65, 40),
(110L, '/assets/pokemons/Weezing.png', 'Weezing', 90, 65),
(111L, '/assets/pokemons/Rhyhorn.png', 'Rhyhorn', 85, 80),
(112L, '/assets/pokemons/Rhydon.png', 'Rhydon', 130, 105),
(113L, '/assets/pokemons/Chansey.png', 'Chansey', 5, 250),
(114L, '/assets/pokemons/Tangela.png', 'Tangela', 100, 65),
(115L, '/assets/pokemons/Kangaskhan.png', 'Kangaskhan', 95, 105),
(116L, '/assets/pokemons/Horsea.png', 'Horsea', 70, 30),
(117L, '/assets/pokemons/Seadra.png', 'Seadra', 95, 55),
(118L, '/assets/pokemons/Goldeen.png', 'Goldeen', 67, 45),
(119L, '/assets/pokemons/Seaking.png', 'Seaking', 92, 80),
(120L, '/assets/pokemons/Staryu.png', 'Staryu', 70, 30),
(121L, '/assets/pokemons/Starmie.png', 'Starmie', 100, 60),
(122L, '/assets/pokemons/Mr._Mime.png', 'Mr. Mime', 100, 40),
(123L, '/assets/pokemons/Scyther.png', 'Scyther', 110, 70),
(124L, '/assets/pokemons/Jynx.png', 'Jynx', 115, 65),
(125L, '/assets/pokemons/Electabuzz.png', 'Electabuzz', 95, 65),
(126L, '/assets/pokemons/Magmar.png', 'Magmar', 100, 65),
(127L, '/assets/pokemons/Pinsir.png', 'Pinsir', 125, 65),
(128L, '/assets/pokemons/Tauros.png', 'Tauros', 100, 75),
(129L, '/assets/pokemons/Magikarp.png', 'Magikarp', 15, 20),
(130L, '/assets/pokemons/Gyarados.png', 'Gyarados', 125, 95),
(131L, '/assets/pokemons/Lapras.png', 'Lapras', 85, 130),
(132L, '/assets/pokemons/Ditto.png', 'Ditto', 48, 48),
(133L, '/assets/pokemons/Eevee.png', 'Eevee', 55, 55),
(134L, '/assets/pokemons/Vaporeon.png', 'Vaporeon', 110, 130),
(135L, '/assets/pokemons/Jolteon.png', 'Jolteon', 110, 65),
(136L, '/assets/pokemons/Flareon.png', 'Flareon', 130, 65),
(137L, '/assets/pokemons/Porygon.png', 'Porygon', 85, 65),
(138L, '/assets/pokemons/Omanyte.png', 'Omanyte', 90, 35),
(139L, '/assets/pokemons/Omastar.png', 'Omastar', 115, 70),
(140L, '/assets/pokemons/Kabuto.png', 'Kabuto', 80, 30),
(141L, '/assets/pokemons/Kabutops.png', 'Kabutops', 115, 60),
(142L, '/assets/pokemons/Aerodactyl.png', 'Aerodactyl', 105, 80),
(143L, '/assets/pokemons/Snorlax.webp', 'Snorlax', 110, 160),
(144L, '/assets/pokemons/Articuno.png', 'Articuno', 95, 90),
(145L, '/assets/pokemons/Zapdos.png', 'Zapdos', 125, 90),
(146L, '/assets/pokemons/Moltres.png', 'Moltres', 125, 90),
(147L, '/assets/pokemons/Dratini.png', 'Dratini', 64, 41),
(148L, '/assets/pokemons/Dragonair.png', 'Dragonair', 84, 61),
(149l, '/assets/pokemons/Dragonite.png', 'Dragonite', 134, 91),
(150L, '/assets/pokemons/Mewtwo.png', 'Mewtwo', 154, 106),
(151L, '/assets/pokemons/Mew.png', 'Mew', 100, 100);

INSERT INTO area (id, name, pokemons, url) VALUES
(1L, 'Pallet Town', 'magikarp poliwag goldeen tentacool staryu bulbasaur charmander squirtle pikachu', '/assets/locations/Pallet_Town_HGSS.png'),
(2L, 'Route 1', 'pidgey rattata', '/assets/locations/Route_1_HGSS.png'),
(3L, 'Viridian City', ' magikarp poliwag goldeen tentacool', '/assets/locations/Viridian_City_HGSS.png'),
(4L, 'Route 2', 'rattata pidgey weedle caterpie nidoran(f) nidoran(M) mr.Mime', '/assets/locations/Route_2_HGSS.png' ),
(5L, 'Viridian Forest', 'weedle caterpie kakuna metapod pikachu pidgey pidgeotto', '/assets/locations/Forest_HGSS.png'),
(6L, 'Digletts cave', ' diglett dugtrio', '/assets/locations/Diglett_Cave_HGSS.png'),
(7L, 'Route 3', 'pidgey spearow rattata sandshrew mankey jigglypuff', '/assets/locations/Route_3_HGSS.png'),
(8L, 'Mt. Moon', 'zubat geodude paras clefairy sandshrew', '/assets/locations/Mt_Moon_1F_HGSS.png'),
(9L, 'Route 4', 'rattata Spearow ekans sandshrew mankey magikarp', '/assets/locations/Route_4_HGSS.png'),
(10L, 'Cerulean Cave', 'golbat magneton hypno arbok sandslash vanomoth dodrio parasect kadabra raichu ditto graveler gloom weepinbell electrode marowak rhydon wigglypuff chansey rhyhorn lickitung magikarp poliwag slowbro krabby seadra seaking mewtwo', '/assets/locations/Cerulean_Cave_1F_HGSS.png'),
(11L, 'Cerulean City', 'magikarp poliwag goldeen psyduck krabby seaking bulbasaur jynx', '/assets/locations/Cerulean_City_HGSS.png'),
(12L, 'Route 5', 'oddish bellsprout pidgey rattata mankey meowth abra jigglypuff pidgeotto nidoran(f) machoke', '/assets/locations/Route_5_HGSS.png'),
(13L, 'Saffron City', 'hitmonlee hitmonchan', '/assets/locations/Saffron_City_HGSS.png'),
(14L, 'Silph Co', 'lapras', '/assets/locations/Silph_Co_1F_HGSS.png'),
(15L, 'Route 6', 'pidgey pidgeotto rattata jigglypuff oddish meowth mankey bellsprout abra psyduck golduck magikarp poliwag goldeen shellder krabby', '/assets/locations/Route_6_HGSS.png'),
(16L, 'Vermillion City', 'magikarp poliwag goldeen shellder krabby tentacool horsea staryu squirtle farfetch''d', '/assets/locations/Vermilion_City_HGSS.png'),
(17L, 'Route 7', 'pidgey pidgeotto rattata jigglypuff oddish bellsprout mankey meowth growlithe vulpix abra', '/assets/locations/Route_7_HGSS.png'),
(18L, 'Celadon City', 'magikarp poliwag goldeen poliwhirl slowpoke eevee', '/assets/locations/Celadon_City_HGSS.png'),
(19L, 'Route 8', 'pidgey pidgeotto rattata ekans sandshrew vulpix jigglypuff mankey meowth growlithe abra kadabra', '/assets/locations/Route_8_HGSS.png'),
(20L, 'Pokemon Tower', 'gastly cubone haunter', '/assets/locations/Lavender_Radio_Tower_HGSS.png'),
(21L, 'Route 10', 'voltorb Spearow ekans sandshrew magnemite rattata nidoran(m) nidoran(f) raticate machop magikarp poliwag goldeen poliwhirl slowpoke krabby horsea kingler', '/assets/locations/Route_10_HGSS.png'),
(22L, 'Rock Tunnel', 'zubat geodude machop onix', '/assets/locations/Rock_Tunnel_1_HGSS.png'),
(23L, 'Power Plant', 'voltorb pikachu magnemite magneton electabuzz raichu grimer muk electrode zapdos', '/assets/locations/Power_Plant_exterior_HGSS.png'),
(24L, 'Route 9', 'rattata Spearow ekans sandshrew nidoran(m) nidoran(f) nidorino nidorina raticate fearow', '/assets/locations/Route_9_HGSS.png'),
(25L, 'Route 11', 'ekans sandshrew Spearow drowzee pidgey rattata pidgeotto raticate magikarp poliwag goldeen shellder krabby tentacool horsea nidorina dugtrio', '/assets/locations/Route_11_HGSS.png'),
(26L, 'Route 12', 'oddish bellsprout pidgey venonat gloom weepinbell pidgeotto farfetch''d slowpoke slowbro magikarp poliwag goldeen tentacool krabby horsea seadra snorlax', '/assets/locations/Route_12_HGSS.png'),
(27L, 'Route 13', 'oddish bellsprout pidgey venonat gloom weepinbell ditto pidgeotto farfetch''d magikarp poliwag goldeen tentacool krabby horsea seadra', '/assets/locations/Route_13_HGSS.png'),
(28L, 'Route 14', 'oddish bellsprout venonat pidgey ditto pidgeotto gloom weepinbell venomoth', '/assets/locations/Route_14_HGSS.png'),
(29L, 'Route 15', 'oddish bellsprout venonat pidgey ditto pidgeotto gloom weepinbell venomoth', '/assets/locations/Route_15_HGSS.png'),
(30L, 'Safari Zone', 'nidoran(m) nidoran(f) exeggcute rhyhorn venonat nidorino nidorina parasect scyther pinsir chansey paras tangela doduo kangskhan cubone tauros marowak venomoth magikarp poliwag goldeen psyduck slowpoke krabby dratini dragonair', '/assets/locations/Pal_Park_HGSS.png'),
(31L, 'Fuchsia City', 'magikarp poliwag goldeen krabby seaking gyarados', '/assets/locations/Fuchsia_City_HGSS.png'),
(32L, 'Route 16', 'spearow Rattata doduo raticate fearow snorlax', '/assets/locations/Route_16_HGSS.png'),
(33L, 'Route 17', 'spearow Rattata doduo fearow ponyta dodrio magikarp poliwag goldeen tentacool krabby shellder', '/assets/locations/Route_17_HGSS.png'),
(34L, 'Route 18', 'spearow doduo raticate fearow rattata magikarp poliwag goldeen tentacool krabby shellder', '/assets/locations/Route_18_HGSS.png'),
(35L, 'Route 19', 'tentacool magikarp poliwag goldeen shellder horsea staryu tentacruel', '/assets/locations/Route_19_HGSS.png'),
(36L, 'Seaform Islands', 'seel horsea krabby shellder staryu slowpoke zubat psyduck golduck slowbro golbat dewgong seadra kingler magikarp poliwag goldeen articuno', '/assets/locations/Seafoam_Islands_B1F_HGSS.png'),
(37L, 'Route 20', 'tentacool magikarp poliwag goldeen shellder horsea staryu tentacruel', '/assets/locations/Route_20_HGSS.png'),
(38L, 'Cinnabar Island', 'magikarp poliwag goldeen shellder horsea staryu tentacool omanyte kabuto aerodactyl electrode seel tangelarhydon muk dewgong', '/assets/locations/Cinnabar_Island_HGSS.png'),
(39L, 'Pokemon Mansion', 'ponyta koffing growlithe vulpix grimer weezing muk rattata raticate magmar ditto', '/assets/locations/Pok%C3%A9mon_Mansion_B1F_FRLG.png'),
(40L, 'Route 21', 'rattata pidgey pidgeotto raticate tangela tentacool magikarp poliwag goldeen shellder horsea staryu tentacruel', '/assets/locations/Route_21_HGSS.png'),
(41L, 'Route 22', 'rattata nidoran(m) nidoran(f) spearow mankey magikarp poliwag goldeen poliwhirl', '/assets/locations/Route_22_HGSS.png'),
(42L, 'Route 23', 'ditto fearow ekans sandshrew spearow arbok sandslash nidorino nidorina mankey primeape magikarp poliwag goldeen slowbro kingler seadra seaking poliwhirl', '/assets/locations/Route_23_FRLG.png'),
(43L, 'Victory Road', 'onix machop zubat geodude golbat machoke marowak graveler venomoth moltres', '/assets/locations/Victory_Road_1F_HGSS.png'),
(44L, 'Route 24', 'weedle caterpie oddish bellsprout pidgey kakuna metapod abra venonat pidgeotto magikarp poliwag goldeen psyduck krabby seaking charmander', '/assets/locations/Route_24_HGSS.png'),
(45L, 'Route 25', 'weedle caterpie oddish bellsprout kakuna metapod pidgey abra venonat pidgeotto magikarp poliwag goldeen psyduck krabby kingler', '/assets/locations/Route_25_HGSS.png'),
(46L, 'Lavender Town', '', '/assets/locations/Lavender_Town_HGSS.png'),
(47L, 'Pewter City', '','/assets/locations/Pewter_City_HGSS.png');